# Generated by Django 2.1 on 2020-04-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='player_name',
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_f_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_l_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_height_f',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_height_i',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_num',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_pos',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_weight',
            field=models.IntegerField(default=''),
        ),
    ]
